# Generated by Django 5.2.5 on 2025-09-05 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_can_create_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('medicine_management', 'Medicine Management'), ('cattle_management', 'Cattle Management'), ('user_management', 'User Management'), ('warehouse_storage', 'Warehouse Storage'), ('reports', 'Reports'), ('settings', 'Settings')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='SectionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('no_access', 'No Access'), ('read_only', 'Read Only'), ('add_records', 'Add Records'), ('edit_records', 'Edit Records'), ('full_access', 'Full Access')], default='no_access', max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this permission')),
                ('granted_by', models.ForeignKey(help_text='User who granted this permission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='users.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['section__display_name', 'user__username'],
                'unique_together': {('user', 'section')},
            },
        ),
    ]
