# Generated by Django 5.2.5 on 2025-09-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_section_sectionpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('finance_manager', 'Finance Manager'), ('head_veterinary', 'Head Veterinary'), ('manager', 'Manager'), ('operator', 'Operator'), ('warehouse_worker', 'Warehouse Worker'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
    ]
