# Generated by Django 5.2.5 on 2025-09-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('finance_manager', 'Finance Manager'), ('procurement', 'Procurement'), ('head_veterinary', 'Head Veterinary'), ('manager', 'Manager'), ('operator', 'Operator'), ('warehouse_worker', 'Warehouse Worker'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
    ]
