# Generated by Django 5.2.5 on 2025-10-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(choices=[('medicine_management', 'Medicine Management'), ('medicine_storage', 'Medicine Storage'), ('cattle_management', 'Cattle Management'), ('user_management', 'User Management'), ('warehouse_storage', 'Warehouse Storage'), ('storage_inventory', 'Storage Inventory'), ('reports', 'Reports'), ('settings', 'Settings')], max_length=50, unique=True),
        ),
    ]
