# Generated by Django 5.2.5 on 2025-10-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(choices=[('medicine_management', 'Medicine Management'), ('medicine_storage', 'Medicine Storage'), ('cattle_management', 'Cattle Management'), ('user_management', 'User Management'), ('warehouse_storage', 'Warehouse Storage'), ('storage_inventory', 'Storage Inventory'), ('finance_management', 'Finance Management'), ('procurement', 'Procurement'), ('feed_management', 'Feed Management'), ('operations', 'Operations'), ('reports', 'Reports'), ('settings', 'Settings')], max_length=50, unique=True),
        ),
    ]
