# Generated by Django 5.2.5 on 2025-10-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_section_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when user was soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete - user is hidden but not removed from database'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('created', 'User Created'), ('updated', 'User Updated'), ('deactivated', 'User Deactivated'), ('activated', 'User Activated'), ('deleted', 'User Deleted'), ('restored', 'User Restored'), ('role_changed', 'Role Changed'), ('password_reset', 'Password Reset')], max_length=20),
        ),
    ]
