# Generated by Django 5.2.5 on 2025-11-11 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Prescription name', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_animal_type', models.CharField(help_text='e.g., Dairy Cattle, Growing Cattle', max_length=100)),
                ('target_weight', models.CharField(blank=True, help_text='Weight range e.g., 500-700kg', max_length=50)),
                ('total_protein', models.DecimalField(decimal_places=2, default=0, help_text='Total protein %', max_digits=5)),
                ('total_energy', models.DecimalField(decimal_places=2, default=0, help_text='Total energy MCal/kg', max_digits=5)),
                ('total_fiber', models.DecimalField(decimal_places=2, default=0, help_text='Total fiber %', max_digits=5)),
                ('cost_per_ton', models.DecimalField(decimal_places=2, default=0, help_text='Cost per ton', max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('inactive', 'Inactive')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_feed_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percentage in mix', max_digits=5)),
                ('kg_per_ton', models.DecimalField(decimal_places=2, help_text='Kilograms per ton', max_digits=7)),
                ('order', models.IntegerField(default=0)),
                ('inventory_item', models.ForeignKey(help_text='Feed ingredient', on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='inventory.feedprescription')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='feedprescription',
            index=models.Index(fields=['status', 'is_active'], name='inventory_f_status_429a49_idx'),
        ),
        migrations.AddIndex(
            model_name='feedprescription',
            index=models.Index(fields=['target_animal_type'], name='inventory_f_target__3254eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prescriptioningredient',
            unique_together={('prescription', 'inventory_item')},
        ),
    ]
