# Generated by Django 5.2.5 on 2025-11-11 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_feedprescription_prescriptioningredient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity consumed in kg or tons', max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('ton', 'Tons')], default='kg', max_length=20)),
                ('target_section', models.CharField(blank=True, help_text='Farm section or animal group', max_length=200)),
                ('animal_count', models.IntegerField(blank=True, help_text='Number of animals fed', null=True)),
                ('consumption_date', models.DateField(help_text='Date of consumption')),
                ('notes', models.TextField(blank=True)),
                ('ingredient_usage', models.JSONField(blank=True, help_text='Auto-calculated ingredient breakdown', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prescription', models.ForeignKey(blank=True, help_text='Feed prescription used (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumption_records', to='inventory.feedprescription')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_consumptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-consumption_date', '-created_at'],
                'indexes': [models.Index(fields=['-consumption_date'], name='inventory_f_consump_8d81a4_idx'), models.Index(fields=['prescription', '-consumption_date'], name='inventory_f_prescri_9a3a55_idx')],
            },
        ),
    ]
