# Generated by Django 5.2.5 on 2025-08-21 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='brand',
            field=models.CharField(blank=True, help_text='Brand or manufacturer', max_length=200),
        ),
        migrations.AddField(
            model_name='medicine',
            name='contraindications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='controlled_substance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='dosage_form',
            field=models.CharField(blank=True, help_text='Injectable, tablet, powder, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='dosage_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(blank=True, help_text='Generic/scientific name', max_length=200),
        ),
        migrations.AddField(
            model_name='medicine',
            name='indication',
            field=models.TextField(blank=True, help_text='What this medicine is used for'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_controlled_drug',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_emergency_medicine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_medicines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicine',
            name='license_number',
            field=models.CharField(blank=True, help_text='Drug license/registration number', max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='location_in_storage',
            field=models.CharField(blank=True, help_text='Physical location in storage', max_length=200),
        ),
        migrations.AddField(
            model_name='medicine',
            name='lot_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='prescription_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='qr_code',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='medicine',
            name='requires_prescription',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='route_of_administration',
            field=models.CharField(blank=True, help_text='IV, IM, oral, topical, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='side_effects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='storage_conditions',
            field=models.TextField(blank=True, help_text='Special storage requirements'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='storage_temperature',
            field=models.CharField(blank=True, help_text='Storage temperature requirements', max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='strength',
            field=models.CharField(blank=True, help_text='Concentration/strength (e.g., 100mg/ml)', max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='supplier_contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='medicine',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='withdrawal_period',
            field=models.CharField(blank=True, help_text='Withdrawal period for food animals', max_length=100),
        ),
    ]
