# Generated by Django 5.2.5 on 2025-09-04 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(help_text='Electronic ID (e.g., 964 001034143697)', max_length=50, unique=True)),
                ('vid', models.CharField(blank=True, help_text='Visual ID if different from EID', max_length=50)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('castrated', 'Castrated')], max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('entry_date', models.DateField(help_text='Date animal entered the system')),
                ('entry_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight at entry (kg)', max_digits=6, null=True)),
                ('current_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Current weight (kg)', max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is animal currently in the system')),
                ('exit_date', models.DateField(blank=True, help_text='Date animal left the system', null=True)),
                ('exit_reason', models.CharField(blank=True, choices=[('sold', 'Sold'), ('deceased', 'Deceased'), ('transferred', 'Transferred'), ('other', 'Other')], max_length=100)),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('under_treatment', 'Under Treatment'), ('quarantine', 'Quarantine')], default='healthy', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_animals', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_animals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['section__section_number', 'eid'],
            },
        ),
        migrations.CreateModel(
            name='CattleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Section name (e.g., FED3, FED4, FED5)', max_length=100)),
                ('section_number', models.IntegerField(help_text='Section number', unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the section')),
                ('capacity', models.IntegerField(help_text='Maximum number of cattle this section can hold')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['section_number'],
            },
        ),
        migrations.CreateModel(
            name='AnimalMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_date', models.DateTimeField()),
                ('reason', models.CharField(blank=True, help_text='Reason for movement', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='cattle.animal')),
                ('moved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_movements', to=settings.AUTH_USER_MODEL)),
                ('from_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals_moved_from', to='cattle.cattlesection')),
                ('to_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals_moved_to', to='cattle.cattlesection')),
            ],
            options={
                'ordering': ['-movement_date'],
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='cattle.cattlesection'),
        ),
        migrations.CreateModel(
            name='FeedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_date', models.DateField(help_text='Date of feed record')),
                ('total_feed_kg', models.DecimalField(decimal_places=2, help_text='Total feed in kg', max_digits=8)),
                ('total_bags', models.DecimalField(blank=True, decimal_places=2, help_text='Number of feed bags', max_digits=6, null=True)),
                ('feed_type', models.CharField(blank=True, help_text='Type of feed used', max_length=100)),
                ('cost_per_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per kg of feed', max_digits=8, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Total feed cost', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_records', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_records', to='cattle.cattlesection')),
            ],
            options={
                'ordering': ['-feed_date', 'section__section_number'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(help_text='Date of health record')),
                ('record_type', models.CharField(choices=[('checkup', 'Regular Checkup'), ('vaccination', 'Vaccination'), ('treatment', 'Treatment'), ('illness', 'Illness'), ('injury', 'Injury'), ('other', 'Other')], max_length=50)),
                ('diagnosis', models.CharField(blank=True, max_length=200)),
                ('treatment', models.TextField(blank=True, help_text='Treatment provided')),
                ('medicine_used', models.CharField(blank=True, help_text='Medicine/drugs administered', max_length=200)),
                ('dosage', models.CharField(blank=True, help_text='Dosage information', max_length=100)),
                ('follow_up_date', models.DateField(blank=True, help_text='Next follow-up date', null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('treatment_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost of treatment', max_digits=8, null=True)),
                ('veterinarian', models.CharField(blank=True, help_text='Veterinarian name', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='cattle.animal')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-record_date', 'animal__eid'],
            },
        ),
        migrations.CreateModel(
            name='CattlePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('read', 'Read Only'), ('add_records', 'Add Records'), ('edit_records', 'Edit Records'), ('full_access', 'Full Access')], max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_cattle_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cattle_permissions', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, help_text='Specific section access, leave blank for all sections', null=True, on_delete=django.db.models.deletion.CASCADE, to='cattle.cattlesection')),
            ],
            options={
                'unique_together': {('user', 'permission_type', 'section')},
            },
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=6)),
                ('measurement_date', models.DateField(help_text='Date of weight measurement')),
                ('gain_loss', models.DecimalField(blank=True, decimal_places=2, help_text='Weight gain/loss from previous measurement', max_digits=6, null=True)),
                ('fcr', models.DecimalField(blank=True, decimal_places=2, help_text='Feed Conversion Ratio', max_digits=6, null=True)),
                ('adg', models.DecimalField(blank=True, decimal_places=2, help_text='Average Daily Gain', max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='cattle.animal')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weight_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-measurement_date', 'animal__eid'],
                'unique_together': {('animal', 'measurement_date')},
            },
        ),
    ]
