# Generated by Django 5.2.5 on 2025-09-08 21:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('order_type', models.CharField(choices=[('medicine', 'Medicine'), ('equipment', 'Equipment'), ('supplies', 'Supplies')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit', models.CharField(default='pieces', max_length=50)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Admin Approval'), ('approved_by_admin', 'Approved by Admin - Pending Finance'), ('approved_by_finance', 'Fully Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Order Created'), ('updated', 'Order Updated'), ('submitted', 'Submitted for Approval'), ('admin_approved', 'Admin Approved'), ('admin_rejected', 'Admin Rejected'), ('finance_approved', 'Finance Approved'), ('finance_rejected', 'Finance Rejected'), ('revision_requested', 'Revision Requested'), ('revision_submitted', 'Revision Submitted'), ('completed', 'Order Completed'), ('cancelled', 'Order Cancelled'), ('comment_added', 'Comment Added'), ('status_changed', 'Status Changed')], max_length=20)),
                ('description', models.TextField()),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('admin', 'Admin Approval'), ('finance', 'Finance Approval')], max_length=10)),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_requested', 'Revision Requested')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('requires_revision', models.BooleanField(default=False)),
                ('revision_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_approvals', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('approval_needed', 'Approval Needed'), ('approved', 'Order Approved'), ('rejected', 'Order Rejected'), ('revision_requested', 'Revision Requested'), ('completed', 'Order Completed'), ('overdue', 'Order Overdue')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.order')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_orde_status_079368_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['requested_by', '-created_at'], name='orders_orde_request_94b8a0_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type', '-created_at'], name='orders_orde_order_t_577592_idx'),
        ),
        migrations.AddIndex(
            model_name='orderactivity',
            index=models.Index(fields=['order', '-created_at'], name='orders_orde_order_i_d052a4_idx'),
        ),
        migrations.AddIndex(
            model_name='orderactivity',
            index=models.Index(fields=['user', '-created_at'], name='orders_orde_user_id_5b5574_idx'),
        ),
        migrations.AddIndex(
            model_name='orderactivity',
            index=models.Index(fields=['activity_type', '-created_at'], name='orders_orde_activit_35a9b0_idx'),
        ),
        migrations.AddIndex(
            model_name='orderapproval',
            index=models.Index(fields=['order', 'stage'], name='orders_orde_order_i_3568db_idx'),
        ),
        migrations.AddIndex(
            model_name='orderapproval',
            index=models.Index(fields=['approver', '-created_at'], name='orders_orde_approve_a400ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderapproval',
            unique_together={('order', 'stage')},
        ),
        migrations.AddIndex(
            model_name='ordernotification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='orders_orde_recipie_780612_idx'),
        ),
    ]
