# Generated by Django 5.2.5 on 2025-09-10 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='revision_reason',
            field=models.TextField(blank=True, help_text='Reason for requesting revision', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='revision_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='revision_requested_by',
            field=models.ForeignKey(blank=True, help_text='User who requested the revision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Admin Approval'), ('approved_by_admin', 'Approved by Admin - Pending Finance'), ('approved_by_finance', 'Fully Approved'), ('rejected', 'Rejected'), ('revision_requested_by_admin', 'Revision Requested by Admin'), ('revision_requested_by_finance', 'Revision Requested by Finance'), ('revision_in_progress', 'Being Revised by Requester'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
