# Generated by Django 5.2.5 on 2025-09-30 23:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_revision_reason_order_revision_requested_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_name',
            field=models.CharField(blank=True, default='', help_text='Name of the item being ordered', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual payment amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Payment method used', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_notes',
            field=models.TextField(blank=True, help_text='Payment notes', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Payment reference/transaction ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quote_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quote amount from procurement', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quote_notes',
            field=models.TextField(blank=True, help_text='Procurement quote notes', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quote_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quote_submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='quote_supplier',
            field=models.CharField(blank=True, help_text='Supplier quoted by procurement', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Manager Approval'), ('approved_by_manager', 'Approved by Manager - Pending Procurement'), ('procurement_quote_submitted', 'Quote Submitted - Pending Manager Approval'), ('quote_approved_by_manager', 'Quote Approved - Pending Finance Payment'), ('payment_completed', 'Payment Completed'), ('rejected', 'Rejected'), ('revision_requested_by_manager', 'Revision Requested by Manager'), ('revision_requested_by_procurement', 'Revision Requested by Procurement'), ('revision_requested_by_finance', 'Revision Requested by Finance'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderactivity',
            name='activity_type',
            field=models.CharField(choices=[('created', 'Order Created'), ('updated', 'Order Updated'), ('submitted', 'Submitted for Approval'), ('manager_approved', 'Manager Approved'), ('manager_rejected', 'Manager Rejected'), ('quote_submitted', 'Quote Submitted by Procurement'), ('quote_approved', 'Quote Approved by Manager'), ('quote_rejected', 'Quote Rejected by Manager'), ('payment_completed', 'Payment Completed by Finance'), ('finance_rejected', 'Finance Rejected'), ('revision_requested', 'Revision Requested'), ('revision_submitted', 'Revision Submitted'), ('completed', 'Order Completed'), ('cancelled', 'Order Cancelled'), ('comment_added', 'Comment Added'), ('status_changed', 'Status Changed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderapproval',
            name='stage',
            field=models.CharField(choices=[('manager_initial', 'Manager Initial Approval'), ('procurement', 'Procurement Quote'), ('manager_quote', 'Manager Quote Approval'), ('finance', 'Finance Payment')], max_length=20),
        ),
        migrations.CreateModel(
            name='QuoteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200)),
                ('quoted_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('delivery_time', models.CharField(blank=True, help_text='Estimated delivery time', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_recommended', models.BooleanField(default=False, help_text="Procurement's recommended option")),
                ('is_selected', models.BooleanField(default=False, help_text='Selected by manager')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_options', to='orders.order')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_quote_options', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['quoted_amount'],
                'indexes': [models.Index(fields=['order', 'is_recommended'], name='orders_quot_order_i_9c023f_idx'), models.Index(fields=['order', 'is_selected'], name='orders_quot_order_i_433084_idx')],
            },
        ),
    ]
