# Generated by Django 5.2.5 on 2025-10-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_item_name_order_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteoption',
            name='buying_company',
            field=models.CharField(blank=True, help_text='Which company is buying', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quoteoption',
            name='supplier_address',
            field=models.TextField(blank=True, help_text='Supplier address', null=True),
        ),
    ]
