# Generated by Django 5.2.5 on 2025-10-03 13:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteOptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('availability', models.CharField(blank=True, help_text='Item availability status', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Item-specific notes', null=True)),
            ],
            options={
                'ordering': ['order_item__id'],
            },
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='orders_orde_order_i_5dc17d_idx',
            old_name='orders_orde_order_i_idx',
        ),
        migrations.AddField(
            model_name='quoteoptionitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_items', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='quoteoptionitem',
            name='quote_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_quotes', to='orders.quoteoption'),
        ),
        migrations.AddIndex(
            model_name='quoteoptionitem',
            index=models.Index(fields=['quote_option', 'order_item'], name='orders_quot_quote_o_8e77b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quoteoptionitem',
            unique_together={('quote_option', 'order_item')},
        ),
    ]
