# Generated by Django 5.2.5 on 2025-10-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_quoteoptionitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteoptionitem',
            name='is_not_available',
            field=models.BooleanField(default=False, help_text='Mark if this item is not available from this supplier'),
        ),
    ]
