# Generated by Django 5.2.5 on 2025-10-20 15:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_add_is_not_available_to_quoteoptionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteoption',
            name='total_with_vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount including VAT', max_digits=10),
        ),
        migrations.AddField(
            model_name='quoteoption',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated VAT amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='quoteoption',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT percentage (e.g., 18.00 for 18%)', max_digits=5),
        ),
    ]
