# Generated by Django 5.2.5 on 2025-10-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_quoteoption_total_with_vat_quoteoption_vat_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteoption',
            name='po_number',
            field=models.CharField(blank=True, help_text='Purchase Order number (e.g., POMF202400001)', max_length=50, null=True, unique=True),
        ),
    ]
