# Generated by Django 5.2.5 on 2026-02-20 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_quoteoption_po_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernotification',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordernotification',
            name='category',
            field=models.CharField(choices=[('order', 'Order'), ('message', 'Message'), ('inventory', 'Inventory'), ('access', 'Access')], default='order', max_length=20),
        ),
        migrations.AddField(
            model_name='ordernotification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ordernotification',
            name='source_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ordernotification',
            name='notification_type',
            field=models.CharField(choices=[('new_message', 'New Message'), ('inventory_alert', 'Inventory Alert'), ('access_changed', 'Access Changed'), ('approval_needed', 'Approval Needed'), ('approved', 'Order Approved'), ('rejected', 'Order Rejected'), ('revision_requested', 'Revision Requested'), ('completed', 'Order Completed'), ('overdue', 'Order Overdue')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ordernotification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='ordernotification',
            index=models.Index(fields=['recipient', 'category', 'is_read', '-created_at'], name='orders_orde_recipie_3b6324_idx'),
        ),
    ]
