# Generated by Django 5.2.5 on 2025-10-27 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Unique employee identification number', max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(choices=[('veterinary', 'Veterinary'), ('cattle_management', 'Cattle Management'), ('feed_management', 'Feed Management'), ('warehouse', 'Warehouse'), ('operations', 'Operations'), ('maintenance', 'Maintenance'), ('security', 'Security'), ('administration', 'Administration'), ('finance', 'Finance'), ('procurement', 'Procurement')], max_length=50)),
                ('position', models.CharField(choices=[('farm_worker', 'Farm Worker'), ('livestock_handler', 'Livestock Handler'), ('equipment_operator', 'Equipment Operator'), ('veterinary_assistant', 'Veterinary Assistant'), ('warehouse_clerk', 'Warehouse Clerk'), ('supervisor', 'Supervisor'), ('technician', 'Technician'), ('driver', 'Driver'), ('security_guard', 'Security Guard'), ('maintenance_worker', 'Maintenance Worker'), ('administrator', 'Administrator'), ('other', 'Other')], max_length=50)),
                ('hire_date', models.DateField(help_text='Date when worker was hired')),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the worker')),
                ('emergency_contact', models.CharField(blank=True, max_length=200)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workers', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_workers', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, help_text='Direct supervisor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_workers', to='workers.worker')),
                ('user_account', models.OneToOneField(blank=True, help_text='Linked system user account if worker has login access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='Item name at time of assignment (cached for history)', max_length=200)),
                ('item_type', models.CharField(choices=[('safety_equipment', 'Safety Equipment'), ('tools', 'Tools'), ('protective_gear', 'Protective Gear'), ('communication_device', 'Communication Device'), ('vehicle', 'Vehicle'), ('uniform', 'Uniform'), ('other', 'Other')], max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, help_text='Quantity assigned', max_digits=10)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='True if item is still assigned, False if returned')),
                ('condition_at_assignment', models.CharField(choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], default='good', max_length=20)),
                ('condition_at_return', models.CharField(blank=True, choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], max_length=20, null=True)),
                ('assignment_notes', models.TextField(blank=True, help_text='Notes when assigning the item')),
                ('return_notes', models.TextField(blank=True, help_text='Notes when returning the item')),
                ('damage_notes', models.TextField(blank=True, help_text='Description of any damage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipment', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(help_text='Item from inventory that is assigned', on_delete=django.db.models.deletion.CASCADE, related_name='worker_assignments', to='inventory.inventoryitem')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_equipment_returns', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_assignments', to='workers.worker')),
            ],
            options={
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Worker Created'), ('updated', 'Worker Updated'), ('status_changed', 'Status Changed'), ('equipment_assigned', 'Equipment Assigned'), ('equipment_returned', 'Equipment Returned'), ('terminated', 'Worker Terminated'), ('reinstated', 'Worker Reinstated')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='workers.equipmentassignment')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_activities', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workers.worker')),
            ],
            options={
                'verbose_name_plural': 'Worker Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['employee_id'], name='workers_wor_employe_5fd967_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['department', 'status'], name='workers_wor_departm_429cc7_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['status'], name='workers_wor_status_c1a993_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentassignment',
            index=models.Index(fields=['worker', 'is_active'], name='workers_equ_worker__850958_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentassignment',
            index=models.Index(fields=['inventory_item', 'is_active'], name='workers_equ_invento_a602ca_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentassignment',
            index=models.Index(fields=['is_active', '-assigned_date'], name='workers_equ_is_acti_a6d0f6_idx'),
        ),
    ]
