# Generated by Django 5.2.5 on 2025-10-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='department',
            field=models.CharField(choices=[('veterinary', 'Veterinary'), ('cattle_management', 'Cattle Management'), ('feed_management', 'Feed Management'), ('warehouse', 'Warehouse'), ('operations', 'Operations'), ('maintenance', 'Maintenance'), ('security', 'Security'), ('administration', 'Administration'), ('finance', 'Finance'), ('procurement', 'Procurement'), ('other', 'Other')], max_length=50),
        ),
    ]
