# Generated by Django 5.2.5 on 2025-10-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_worker_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentassignment',
            name='item_type',
            field=models.CharField(blank=True, choices=[('safety_equipment', 'Safety Equipment'), ('tools', 'Tools'), ('protective_gear', 'Protective Gear'), ('communication_device', 'Communication Device'), ('vehicle', 'Vehicle'), ('uniform', 'Uniform'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
